volumes:
  blockchain:
    name: btc-data

services:

  chain:
    container_name: tbtc-chain
    build: .
    mem_limit: 2048m
    cpus: 0.8
    healthcheck:
      test: ["CMD", "bitcoin-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.bitcoin
    environment:
      UACOMMENT: $UACOMMENT
      BLOCKPRODUCTIONDELAY: ${BLOCKPRODUCTIONDELAY:-30}
      MINERENABLED: ${MINERENABLED:-0}
      NBITS: $NBITS
      MINETO: ${MINETO:-tb1qk4pq0rh75qtph47wlufhyss43flhvhvwe4zt8a} # miner private key path is m/84'/1'/0'/0/0 of test wallet wallet "margin radio diamond leg loud street announce guitar video shiver speed eyebrow"
      PRIVKEY: ${PRIVKEY:-cNDhpWanXGyCed6U7eBNqRN3EyB7mEUbqm19tA7z5ho6BiNaPfmy} 
      SIGNETCHALLENGE: ${SIGNETCHALLENGE:-512102a3f8184701a033e5f8faa295647374b0bbc868082240d6e7ad8e9ecb0d86e6d451ae}
      EXTERNAL_IP: $EXTERNAL_IP
      RPCUSER: ${RPCUSER:-rpcuser}
      RPCPASSWORD: ${RPCPASSWORD:-rpcpassword}
      ADDNODE: ${ADDNODE:-15.235.3.238:38333}
    ports:
      - 38332:38332
      - 38333:38333
    networks:
      - btcnetwork

networks:
  btcnetwork:
    external: false
    name: btcnetwork
