FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /usr/local/app/

RUN apt-get update \
    && apt-get install -y curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -Ls https://github.com/block-core/bitcoin-custom-signet/releases/download/#{VERSION}#/faucet-api-#{VERSION}#-linux-x64.tar.gz \
    | tar -xvz -C .

EXPOSE 9910
ENTRYPOINT ["dotnet", "faucet-api.dll"]