services:
  faucet-api:
    container_name: faucet-api
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 1024m
    cpus: 0.200
    environment:
      ASPNETCORE_URLS: http://+:5500
      ASPNETCORE_ENVIRONMENT: Development
      Logging__LogLevel__Default: Debug
      Bitcoin__Mnemonic: "margin radio diamond leg loud street announce guitar video shiver speed eyebrow"
      Bitcoin__Network: "TestNet"
      Bitcoin__FeeRate: 10001
      Bitcoin__ChangeAddressIndex: 0
      Bitcoin__RpcUrl: "http://tbtc-chain:38332"
      Bitcoin__RpcUser: "rpcuser"
      Bitcoin__RpcPassword: "rpcpassword"
      Bitcoin__RpcWallet: "custom_signet"
    restart: unless-stopped
    ports:
      - "5500:5500"
    networks:
      - btcnetwork

networks:
  btcnetwork:
    external: true
    name: btcnetwork
