version: '3.8'

services:
  faucet-api:
    container_name: faucet-api
    image: blockcore/faucet-api:1.0.3
    mem_limit: 1024m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: faucettmp.angor.io
      VIRTUAL_PORT: 5500
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: faucettmp.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:5500
      Logging__LogLevel__Default: Debug
      DataConfig__UseDefaultPath: "true"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy